### ISSUE TITLE
loading没有？

### ISSUE THREAD

**Issue by catroom** [jenly1314/WanAndroid#1]
我看了代码，并没有loading的代码实现？我想加个dialog。但是dialog依附actvity的上下文。我一直在寻找一个好方法，例如了平时需要adater里面弹出一个弹窗，做相关逻辑操作，这个操作是不是要再封装一层？期待你的回复

**Comment by jenly1314** [comment]
Resource 监听回调时 OnHandleCallback 中有onLoading方法，在里面实现loading逻辑即可。 BaseActivity中也有OnHandleCallback 的通用回调接口实现 OnCallback。
